# Welcome! 
# 
# Step 1: Come up with a short name for your XBlock. For example, if 
# your XBlock plays audio files, 'audio' is a good name. 
short-name : done
# Step 2: Create a repository on github for your XBlock. In the above
# case, I strongly recommend the short name, followed by 'XBlock,' in 
# camelcase. Do not initialize this repo. We'll do it for you
github : git@github.com:pmitros/DoneXBlock.git
# Step 3: Give a short description of this XBlock
description : Lets a student mark they've finished an activity
# Step 4: Give a multiline description. Keep the 2 line indent, please. 
overview : |
  FutureLearn uses this kind of thing to great effect. Students can 
  read text, watch videos, etc., and mark when their done. Honor 
  code grading, and convenient progress indication. 
# Once you're done, hit save, and watch the magic happen!
